version: '3.8'
services:
  db:
    build: .
    container_name: docker-mysql-for-household-expenses-api
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expenses_manager_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    image: mysql:8.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
